# Generated by Django 5.0 on 2023-12-18 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="info",
            old_name="is_deleted",
            new_name="is_buy",
        ),
    ]
